<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21345" started-at="2016-08-15T07:45:30Z" finished-at="2016-08-15T07:45:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21345" started-at="2016-08-15T07:45:30Z" finished-at="2016-08-15T07:45:52Z">
      <class name="test.account.MyAccountTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:test.account.MyAccountTest@4de8b406]" name="beforeClass" is-config="true" duration-ms="17527" started-at="2016-08-15T09:45:30Z" finished-at="2016-08-15T09:45:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="verifyArea()[pri:0, instance:test.account.MyAccountTest@4de8b406]" name="verifyArea" duration-ms="127" started-at="2016-08-15T09:45:48Z" finished-at="2016-08-15T09:45:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyArea -->
        <test-method status="FAIL" signature="verifyProfileAccount()[pri:0, instance:test.account.MyAccountTest@4de8b406]" name="verifyProfileAccount" duration-ms="59" started-at="2016-08-15T09:45:48Z" depends-on-methods="test.account.MyAccountTest.verifyArea" finished-at="2016-08-15T09:45:48Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at library.util.Verification.print(Verification.java:23)
	at library.util.Verification.verifyString(Verification.java:39)
	at test.account.MyAccountTest.verifyProfileAccount(MyAccountTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:745)
	at org.testng.TestRunner.run(TestRunner.java:599)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:174)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:78)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProfileAccount -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:test.account.MyAccountTest@4de8b406]" name="afterClass" is-config="true" duration-ms="3588" started-at="2016-08-15T09:45:48Z" finished-at="2016-08-15T09:45:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- test.account.MyAccountTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
