<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21574" started-at="2016-08-08T08:38:55Z" finished-at="2016-08-08T08:39:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21574" started-at="2016-08-08T08:38:55Z" finished-at="2016-08-08T08:39:16Z">
      <class name="test.LoginU">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:test.LoginU@6d8a00e3]" name="beforeClass" is-config="true" duration-ms="12936" started-at="2016-08-08T10:38:55Z" finished-at="2016-08-08T10:39:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="f()[pri:0, instance:test.LoginU@6d8a00e3]" name="f" duration-ms="7877" started-at="2016-08-08T10:39:08Z" finished-at="2016-08-08T10:39:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[You are logged in.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: You are logged in.
	at test.LoginU.f(LoginU.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:745)
	at org.testng.TestRunner.run(TestRunner.java:599)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:174)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:78)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:test.LoginU@6d8a00e3]" name="afterClass" is-config="true" duration-ms="725" started-at="2016-08-08T10:39:16Z" finished-at="2016-08-08T10:39:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- test.LoginU -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
